### ISSUE TITLE
Reconfigure Disqus to correct URL

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#178] opened 2017-08-23 13:55 UTC
- [x] Reconfigure Disqus to the correct URL

**Comment by samhstn** [comment] 2017-08-24 09:40
Depends on #188, will start once the new url is set up

**Comment by samhstn** [comment] 2017-08-25 16:13
Now depends on #226

**Comment by samhstn** [comment] 2017-09-04 09:58
Currently disqus comments made on one resource page are showing up on other resource pages.

**Comment by samhstn** [comment] 2017-09-04 11:45
Sent a message to their support team about the issue. Will publish what they send back here when I hear from them https://help.disqus.com/customer/portal/emails/completed

They are PA time so, may respond by the end of the day, if not, we should get a message by tomorrow

**Comment by samhstn** [comment] 2017-09-06 13:28
Received a message back siting me to the docs saying that the problem was that I had multiple identifiers pointing to the same thread.

I sent through these screenshots showing that actually these are unique.

![screen shot 2017-09-06 at 14 14 07](https://user-images.githubusercontent.com/15983736/30114404-a7f79666-930f-11e7-8ff1-5bf16f46d955.png)
![screen shot 2017-09-06 at 14 22 39](https://user-images.githubusercontent.com/15983736/30114405-a7fe8b38-930f-11e7-8062-68aea2bd1bf6.png)

**Comment by reddog** [comment] 2017-09-06 15:01
@shouston3 Is `newsite-6` the name of the *forum* as detailed in Disqus (seems a little generic, so just wanted to check)?  https://help.disqus.com/customer/portal/articles/472098-javascript-configuration-variables

```
shortname

Tells the Disqus service your forum's shortname, which is the unique identifier for your website as registered on Disqus. If undefined, the Disqus embed will not load.

Usage: Specify your forum shortname by replacing EXAMPLE in the following line of code:

s.src = '//EXAMPLE.disqus.com/embed.js';  // IMPORTANT: Replace EXAMPLE with your forum shortname!
```

**Comment by samhstn** [comment] 2017-09-06 15:08
I originally changed this to ldmw, but with the renaming coming up I can change this to the final name later.

This name is probably not the problem though as all of the chats are coming through.

**Comment by reddog** [comment] 2017-09-07 08:32
@shouston3 Whatever forum shortcode you use, it has to be that which is

> the unique identifier for your website as registered on Disqus

by the looks of it.  Is that the case?  Is `newsite-6` the registered forum shortcode?

**Comment by samhstn** [comment] 2017-09-07 09:31
@reddog the website shortname is `newsite-6`.
![screen shot 2017-09-07 at 10 28 32](https://user-images.githubusercontent.com/15983736/30156378-6327e52e-93b7-11e7-85de-0a73a6e4ef03.png)
My only references to `newsite-6` in the javascript snippet were something I was told to paste in by disqus

**Comment by samhstn** [comment] 2017-09-07 09:35
Got another message back from the disqus support team after sending over screen shots of my configuration:

-- DISQUS --

I’m attaching an image of the thread details for the thread that is loading on both of these urls.

It appears that for some reason, the correct thread is not loading. This could be because the current identifier is still associated with the ‘http://www.londonminds.co.uk/’ url, or because the line of code assigning the url variable is not executing.

I would recommend re-pasting the embed code from here: https://help.disqus.com/customer/portal/articles/472097

As well as removing the “this.page.title” variable, so that the embed code is as close to default as possible. Then we can check to see if the correct thread is loading.

-- ATTACHMENT --

![screenshot_2017-09-06_13 07 34](https://user-images.githubusercontent.com/15983736/30156658-29617ade-93b8-11e7-9d83-b9aaf98f686b.png)

**Comment by reddog** [comment] 2017-09-07 09:48
@shouston3 Looks like a useful reply & screenshot.  Is it all of the different `identifers` that's the root cause?

**Comment by samhstn** [comment] 2017-09-07 09:55
I'm not really sure to be honest, but looks like it could be.
It seems that I have enough info from disqus to work with.
I'm going to have a play around with different config options on a heroku staging site until it works.
Then make a pull request, get it merged and see if it works on the main site.

**Comment by samhstn** [comment] 2017-09-07 12:26
Finally got it working on the staging site [here](https://ldmw-staging.herokuapp.com/resources/sleepio/) and [here](https://ldmw-staging.herokuapp.com/resources/sleep-school/)

Got it working on staging by creating an entirely new account and with the following config:

```javascript
var disqus_config = function () {
  this.page.url = 'https://ldmw-staging.herokuapp.com/resources/{{page.slug}}';
  this.page.identifier = 'resource{{page.id}}';
};
```

Which is what I had before, but this time it worked 😕 

I'll look at adding the same again, but for the live site

**Comment by samhstn** [comment] 2017-09-07 12:31
I'll add this on to the live site once we have confirmed the new name so that it is named correctly in disqus.

**Closed as completed** 2017-09-20 08:30 UTC
Labels: external-dependency, priority-3, T4h, technical, please-test
