### ISSUE TITLE
Chevron stays pink after being clicked on android

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#559] opened 2017-10-09 11:42 UTC

**Comment by katbow** [comment] 2017-10-10 09:59
note for myself: this is on the homepage on the hero image. Also happened on iPhone 6 when I checked it out.

**Comment by katbow** [comment] 2017-10-10 15:29
This is a known bug on mobile devices called sticky hover. The usual fix is to use JavaScript to end the touch event which puts the state back to normal. But I feel **certain** there is a css only fix for this.

**Comment by ellemindwave** [comment] 2017-10-12 15:21
@katbow @Danwhy the chevron doesn't seem to change colour or do anything on iphone 6 chrome now when I click it on staging.

On the live site it still jumps but doesn't turn pink either

**Comment by katbow** [comment] 2017-10-12 15:31
@ellemindwave is this only on your actual device? I can't recreate it when I am using iPhone 6 on chrome dev tools, or using chrome on my android device. Do you mean that is is not even scrolling down to the topics?

And it shouldn't turn pink now, as hover state doesn't really exist on mobile devices, unless as the sticky hover bug which this was originally correcting.

**Comment by katbow** [comment] 2017-10-13 15:17
@ellemindwave this fixes the chevron not scrolling down on iphone chrome. Let me know if you also want the active colour changed.

**Comment by katbow** [comment] 2017-10-13 15:40
confirmed with @ellemindwave to make the active colour pink

**Comment by katbow** [comment] 2017-10-13 16:06
@ellemindwave turns out it wasn't as simple as I thought 😆 😭 . Because the `<i>` tag defines the colour & is contained within another `<a>` tag, you can't directly click on this on mobile. You need to be able to do this to make the `<i>` active, so that there will be the colour change. Sorry about that, I thought it was going to be a quick fix 🙁!

**Closed as completed** 2017-10-26 14:32 UTC
Labels: bug, priority-4, T1h, please-test, UI
